title: mutakin portfolio
baseURL: /
params:
  accent_color: blue
  color_scheme: light
  footer:
    content: '&copy; mutakin 2020. All rights reserved.'
    has_social: true
    links: []
  header:
    has_nav: true
    title: mutakin
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
